basePath: /
definitions:
  server.Response:
    properties:
      data:
        description: data
      error:
        description: error
        type: string
      message:
        description: message
        type: string
      status:
        description: success | error | failed
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: Boilerplate API
  title: Boilerplate API
  version: "1.0"
paths:
  /:
    get:
      description: Hello World
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/server.Response'
      summary: Hello World
      tags:
      - Hello World
swagger: "2.0"
